import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ClipboardCheck, FileSignature, RefreshCw, ShieldCheck, Truck, Workflow, X } from "lucide-react";
import { toast } from "sonner";
import { api, unwrapList } from "@/lib/api";
import { Button } from "@/components/kit/Button";
import { Card, PageHeader, StatCard } from "@/components/kit/Card";
import { DataTable } from "@/components/kit/DataTable";
import type { Row } from "@/components/kit/DataTable";
import { col } from "@/lib/scm";

export const Route = createFileRoute("/operations")({ component: OperationsPage });

function OperationsPage() {
  const qc = useQueryClient();
  const inbox = useQuery({ queryKey: ["/operations/approvals/inbox"], queryFn: async () => unwrapList(await api.get("/operations/approvals/inbox")) });
  const exceptions = useQuery({ queryKey: ["/operations/match/exceptions"], queryFn: async () => unwrapList(await api.get("/operations/match/exceptions?status=Open")) });
  const replenishment = useQuery({ queryKey: ["/operations/inventory/replenishment"], queryFn: async () => unwrapList(await api.get("/operations/inventory/replenishment")) });
  const putaway = useQuery({ queryKey: ["/operations/warehouse/putaway"], queryFn: async () => unwrapList(await api.get("/operations/warehouse/putaway?status=Open")) });
  const fulfillment = useQuery({ queryKey: ["/operations/warehouse/fulfillment"], queryFn: async () => unwrapList(await api.get("/operations/warehouse/fulfillment")) });
  const cycleCounts = useQuery({ queryKey: ["/operations/warehouse/cycle-counts"], queryFn: async () => unwrapList(await api.get("/operations/warehouse/cycle-counts?status=Pending%20Approval")) });
  const adjustments = useQuery({ queryKey: ["/operations/warehouse/adjustments"], queryFn: async () => unwrapList(await api.get("/operations/warehouse/adjustments?status=Pending%20Approval")) });
  const contractAlerts = useQuery({ queryKey: ["/operations/contracts/alerts"], queryFn: async () => api.get<{ documents?: Row[]; obligations?: Row[] }>("/operations/contracts/alerts") });
  const budgetTransfers = useQuery({ queryKey: ["/operations/budget/transfers"], queryFn: async () => unwrapList(await api.get("/operations/budget/transfers?status=Pending%20Approval")) });
  const riskSummary = useQuery({ queryKey: ["/operations/supplier-risk/summary"], queryFn: async () => unwrapList(await api.get("/operations/supplier-risk/summary")) });
  const budgetAlerts = useQuery({ queryKey: ["/operations/budget/alerts"], queryFn: async () => unwrapList(await api.get("/operations/budget/alerts")) });
  const decide = useMutation({ mutationFn: ({ id, decision }: { id: string; decision: string }) => api.post(`/operations/approvals/${id}/decision`, { decision }), onSuccess: () => { toast.success("Approval task updated"); void qc.invalidateQueries({ queryKey: ["/operations/approvals/inbox"] }); }, onError: (e: Error) => toast.error(e.message) });
  const resolve = useMutation({ mutationFn: (id: string) => api.post(`/operations/match/exceptions/${id}/resolve`, { resolution: "Reviewed and accepted by operations" }), onSuccess: () => { toast.success("Match exception resolved"); void qc.invalidateQueries({ queryKey: ["/operations/match/exceptions"] }); }, onError: (e: Error) => toast.error(e.message) });
  const approveWorkflow = useMutation({ mutationFn: ({ path, id }: { path: string; id: string }) => api.post(`/operations/${path}/${id}/approve`), onSuccess: () => { toast.success("Workflow approved"); void qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  const advanceFulfillment = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api.post(`/operations/warehouse/fulfillment/${id}/advance`, { status }), onSuccess: () => { toast.success("Fulfillment stage updated"); void qc.invalidateQueries({ queryKey: ["/operations/warehouse/fulfillment"] }); }, onError: (e: Error) => toast.error(e.message) });
  const refresh = () => { void inbox.refetch(); void exceptions.refetch(); void replenishment.refetch(); void putaway.refetch(); void fulfillment.refetch(); void cycleCounts.refetch(); void adjustments.refetch(); void contractAlerts.refetch(); void budgetTransfers.refetch(); void riskSummary.refetch(); void budgetAlerts.refetch(); };
  return <div>
    <PageHeader title="Operations Control Center" description="Approval work, invoice exceptions and inventory replenishment in one queue." actions={<Button variant="subtle" onClick={refresh}><RefreshCw className="h-3.5 w-3.5" /> Refresh</Button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3 xl:grid-cols-7"><StatCard label="Approval tasks" value={String(inbox.data?.length ?? 0)} tone="iris" icon={<ShieldCheck className="h-5 w-5" />} /><StatCard label="Open match exceptions" value={String(exceptions.data?.length ?? 0)} tone="danger" icon={<Workflow className="h-5 w-5" />} /><StatCard label="Replenishment" value={String(replenishment.data?.length ?? 0)} tone="warning" icon={<Truck className="h-5 w-5" />} /><StatCard label="Put-away tasks" value={String(putaway.data?.length ?? 0)} tone="info" /><StatCard label="Contract alerts" value={String((contractAlerts.data?.documents?.length ?? 0) + (contractAlerts.data?.obligations?.length ?? 0))} tone="warning" icon={<FileSignature className="h-5 w-5" />} /><StatCard label="Budget alerts" value={String(budgetAlerts.data?.length ?? 0)} tone="warning" /><StatCard label="Supplier risk reviews" value={String(riskSummary.data?.filter((r) => Number(r.riskScore ?? 0) >= 60).length ?? 0)} tone="danger" /></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Approval inbox</h2><DataTable rows={inbox.data as Row[] ?? []} columns={[col.text("entityType", "Entity"), col.text("entityId", "Reference"), col.text("approverRole", "Required role"), col.date("dueAt", "Due")]} loading={inbox.isFetching} searchKeys={["entityType", "entityId", "approverRole"]} rowActions={(row) => <><Button size="sm" variant="subtle" onClick={() => decide.mutate({ id: String(row.id), decision: "approve" })}><Check className="h-3.5 w-3.5 text-success" /> Approve</Button><Button size="sm" variant="subtle" onClick={() => decide.mutate({ id: String(row.id), decision: "reject" })}><X className="h-3.5 w-3.5 text-destructive" /> Reject</Button></>} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Three-way match exceptions</h2><DataTable rows={exceptions.data as Row[] ?? []} columns={[col.text("invoiceId", "Invoice"), col.text("type", "Exception"), col.text("severity", "Severity"), col.text("message", "Details")]} loading={exceptions.isFetching} searchKeys={["invoiceId", "type", "message"]} rowActions={(row) => <Button size="sm" variant="subtle" onClick={() => resolve.mutate(String(row.id))}>Resolve</Button>} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Replenishment suggestions</h2><DataTable rows={replenishment.data as Row[] ?? []} columns={[col.text("item", "Item"), col.text("sku", "SKU"), col.num("available", "Available"), col.num("suggestedQuantity", "Suggested order")]} loading={replenishment.isFetching} searchKeys={["item", "sku", "warehouseId"]} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Warehouse execution</h2><DataTable rows={putaway.data as Row[] ?? []} columns={[col.code("taskId", "Task"), col.text("goodsReceiptId", "Receipt"), col.text("binId", "Bin"), col.num("quantity", "Qty")]} loading={putaway.isFetching} searchKeys={["taskId", "goodsReceiptId", "binId"]} rowActions={(row) => <Button size="sm" variant="subtle" onClick={() => api.post(`/operations/warehouse/putaway/${String(row.id)}/complete`).then(() => { toast.success("Put-away completed"); void qc.invalidateQueries({ queryKey: ["/operations/warehouse/putaway"] }); }).catch((e: Error) => toast.error(e.message))}>Complete</Button>} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Pick / pack / ship</h2><DataTable rows={fulfillment.data as Row[] ?? []} columns={[col.text("orderId", "Order"), col.status("status"), col.date("pickedAt", "Picked"), col.date("packedAt", "Packed")]} loading={fulfillment.isFetching} searchKeys={["orderId", "status"]} rowActions={(row) => { const status = String(row.status); const next = status === "Pick Pending" ? "Picked" : status === "Picked" ? "Packed" : status === "Packed" ? "Shipped" : ""; return next ? <Button size="sm" variant="subtle" onClick={() => advanceFulfillment.mutate({ id: String(row.id), status: next })}>{next}</Button> : null; }} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Warehouse approvals</h2><DataTable rows={[...(cycleCounts.data as Row[] ?? []), ...(adjustments.data as Row[] ?? [])]} columns={[col.text("countId", "Count / Adjustment"), col.text("inventoryId", "Inventory"), col.num("variance", "Variance"), col.status("status")]} loading={cycleCounts.isFetching || adjustments.isFetching} searchKeys={["countId", "adjustmentId", "inventoryId", "status"]} rowActions={(row) => <Button size="sm" variant="subtle" onClick={() => approveWorkflow.mutate({ path: row.countId ? "warehouse/cycle-counts" : "warehouse/adjustments", id: String(row.id) })}><ClipboardCheck className="h-3.5 w-3.5" /> Approve</Button>} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Contract renewal & compliance alerts</h2><DataTable rows={[...(contractAlerts.data?.documents ?? []), ...(contractAlerts.data?.obligations ?? [])]} columns={[col.text("documentType", "Type"), col.text("title", "Obligation"), col.date("expiresAt", "Expiry"), col.date("dueDate", "Due"), col.status("status")]} loading={contractAlerts.isFetching} searchKeys={["documentType", "title", "status"]} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Budget transfer approvals</h2><DataTable rows={budgetTransfers.data as Row[] ?? []} columns={[col.code("transferId", "Transfer"), col.text("fromBudgetId", "From"), col.text("toBudgetId", "To"), col.money("amount", "Amount"), col.text("reason", "Reason")]} loading={budgetTransfers.isFetching} searchKeys={["transferId", "fromBudgetId", "toBudgetId", "reason"]} rowActions={(row) => <Button size="sm" variant="subtle" onClick={() => approveWorkflow.mutate({ path: "budget/transfers", id: String(row.id) })}>Approve</Button>} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Budget variance alerts</h2><DataTable rows={budgetAlerts.data as Row[] ?? []} columns={[col.text("category", "Budget"), col.num("allocated", "Allocated"), col.num("spent", "Spent"), col.num("reserved", "Reserved"), col.num("utilization", "Utilization %"), col.status("alert", "Alert")]} loading={budgetAlerts.isFetching} searchKeys={["category", "year", "alert"]} /></div></Card>
      <Card><div className="p-4"><h2 className="mb-3 text-sm font-bold">Supplier risk & concentration</h2><DataTable rows={riskSummary.data as Row[] ?? []} columns={[col.text("supplierId", "Supplier"), col.num("riskScore", "Risk score"), col.status("sanctionsStatus", "Sanctions"), col.text("financialHealth", "Financial health"), col.num("concentrationScore", "Concentration %")]} loading={riskSummary.isFetching} searchKeys={["supplierId", "riskScore", "sanctionsStatus", "financialHealth"]} /></div></Card>
    </div>
  </div>;
}
