import { Router } from "express";
import { OperationsController } from "../controllers/operations.controller.js";

const router = Router();
const c = new OperationsController();
router.get("/approval-rules", c.rules.bind(c));
router.post("/approval-rules", c.createRule.bind(c));
router.put("/approval-rules/:id", c.updateRule.bind(c));
router.delete("/approval-rules/:id", c.deleteRule.bind(c));
router.get("/approvals/inbox", c.inbox.bind(c));
router.post("/approvals/:id/decision", c.decide.bind(c));
router.get("/match/exceptions", c.exceptions.bind(c));
router.post("/match/:invoiceId/run", c.match.bind(c));
router.post("/match/exceptions/:id/resolve", c.resolveException.bind(c));
router.get("/portal/invitations", c.invitations.bind(c));
router.post("/portal/invitations", c.inviteSupplier.bind(c));
router.get("/portal/rfqs", c.portalRfqs.bind(c));
router.post("/rfqs/:rfqId/invitations", c.inviteToRfq.bind(c));
router.get("/rfqs/:rfqId/comparison", c.comparison.bind(c));
router.post("/quotes/:quoteId/score", c.scoreQuote.bind(c));
router.get("/inventory/replenishment", c.replenishment.bind(c));
router.post("/inventory/reservations", c.reserve.bind(c));
router.post("/inventory/reservations/:id/release", c.release.bind(c));
router.get("/inventory/transfers", c.transfers.bind(c));
router.post("/inventory/transfers", c.transfer.bind(c));
router.get("/audit-logs", c.audit.bind(c));
router.get("/warehouse/bins", c.bins.bind(c));
router.post("/warehouse/bins", c.createBin.bind(c));
router.get("/warehouse/putaway", c.putaway.bind(c));
router.post("/warehouse/putaway", c.createPutaway.bind(c));
router.post("/warehouse/putaway/:id/complete", c.completePutaway.bind(c));
router.get("/warehouse/fulfillment", c.fulfillment.bind(c));
router.post("/warehouse/fulfillment", c.createFulfillment.bind(c));
router.post("/warehouse/fulfillment/:id/advance", c.advanceFulfillment.bind(c));
router.get("/warehouse/cycle-counts", c.cycleCounts.bind(c));
router.post("/warehouse/cycle-counts", c.createCycleCount.bind(c));
router.post("/warehouse/cycle-counts/:id/submit", c.submitCycleCount.bind(c));
router.post("/warehouse/cycle-counts/:id/approve", c.approveCycleCount.bind(c));
router.get("/warehouse/adjustments", c.adjustments.bind(c));
router.post("/warehouse/adjustments", c.createAdjustment.bind(c));
router.post("/warehouse/adjustments/:id/approve", c.approveAdjustment.bind(c));
router.get("/contracts/alerts", c.contractAlerts.bind(c));
router.get("/contracts/:id/overview", c.contractOverview.bind(c));
router.post("/contracts/:id/versions", c.contractVersion.bind(c));
router.post("/contracts/:id/obligations", c.contractObligation.bind(c));
router.get("/budget/reservations", c.budgetReservations.bind(c));
router.post("/budget/reservations", c.reserveBudget.bind(c));
router.get("/budget/:id/availability", c.budgetAvailability.bind(c));
router.get("/budget/transfers", c.budgetTransfers.bind(c));
router.post("/budget/transfers", c.createBudgetTransfer.bind(c));
router.post("/budget/transfers/:id/approve", c.approveBudgetTransfer.bind(c));
router.get("/budget/alerts", c.budgetAlerts.bind(c));
router.post("/budget/rollover", c.rolloverBudgets.bind(c));
router.get("/supplier-risk/summary", c.supplierRiskSummary.bind(c));
router.get("/supplier-risk/compliance", c.supplierCompliance.bind(c));
router.post("/supplier-risk/compliance", c.createSupplierCompliance.bind(c));
router.post("/supplier-risk/:id/assess", c.supplierRisk.bind(c));
export default router;
