/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CarriersRouteImport } from './routes/carriers'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as GoodsReceiptsRouteImport } from './routes/goods-receipts'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as RequisitionsRouteImport } from './routes/requisitions'
import { Route as RfqsRouteImport } from './routes/rfqs'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WarehousesRouteImport } from './routes/warehouses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersRoute = CarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsReceiptsRoute = GoodsReceiptsRouteImport.update({
  id: '/goods-receipts',
  path: '/goods-receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsRoute = RequisitionsRouteImport.update({
  id: '/requisitions',
  path: '/requisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsRoute = RfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/carriers': typeof CarriersRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/goods-receipts': typeof GoodsReceiptsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/requisitions': typeof RequisitionsRoute
  '/rfqs': typeof RfqsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/carriers': typeof CarriersRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/goods-receipts': typeof GoodsReceiptsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/requisitions': typeof RequisitionsRoute
  '/rfqs': typeof RfqsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/carriers': typeof CarriersRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/goods-receipts': typeof GoodsReceiptsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/requisitions': typeof RequisitionsRoute
  '/rfqs': typeof RfqsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/budget'
    | '/carriers'
    | '/contracts'
    | '/customers'
    | '/goods-receipts'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/logistics'
    | '/orders'
    | '/payments'
    | '/requisitions'
    | '/rfqs'
    | '/shipments'
    | '/suppliers'
    | '/users'
    | '/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/budget'
    | '/carriers'
    | '/contracts'
    | '/customers'
    | '/goods-receipts'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/logistics'
    | '/orders'
    | '/payments'
    | '/requisitions'
    | '/rfqs'
    | '/shipments'
    | '/suppliers'
    | '/users'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/budget'
    | '/carriers'
    | '/contracts'
    | '/customers'
    | '/goods-receipts'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/logistics'
    | '/orders'
    | '/payments'
    | '/requisitions'
    | '/rfqs'
    | '/shipments'
    | '/suppliers'
    | '/users'
    | '/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BudgetRoute: typeof BudgetRoute
  CarriersRoute: typeof CarriersRoute
  ContractsRoute: typeof ContractsRoute
  CustomersRoute: typeof CustomersRoute
  GoodsReceiptsRoute: typeof GoodsReceiptsRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  RequisitionsRoute: typeof RequisitionsRoute
  RfqsRoute: typeof RfqsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SuppliersRoute: typeof SuppliersRoute
  UsersRoute: typeof UsersRoute
  WarehousesRoute: typeof WarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers': {
      id: '/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof CarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods-receipts': {
      id: '/goods-receipts'
      path: '/goods-receipts'
      fullPath: '/goods-receipts'
      preLoaderRoute: typeof GoodsReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions': {
      id: '/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof RequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs': {
      id: '/rfqs'
      path: '/rfqs'
      fullPath: '/rfqs'
      preLoaderRoute: typeof RfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BudgetRoute: BudgetRoute,
  CarriersRoute: CarriersRoute,
  ContractsRoute: ContractsRoute,
  CustomersRoute: CustomersRoute,
  GoodsReceiptsRoute: GoodsReceiptsRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  RequisitionsRoute: RequisitionsRoute,
  RfqsRoute: RfqsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SuppliersRoute: SuppliersRoute,
  UsersRoute: UsersRoute,
  WarehousesRoute: WarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
